aesthetic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('goods/', include('goods.urls')),
    path('orders/', include('orders.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='all-products'),
    path('cart/', views.cart, name='cart'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add-to-cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update-cart/', views.update_cart, name='update_cart'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_list, name='list'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <title>Aesthetic</title>
</head>
<body class="container">
<ul class="list-group list-group-horizontal">
    <li class="list-group-item">
        <a href ="{% url 'home' %}">Главная</a>
        {% if request.user.is_authenticated %}
            Привет, {{ user.name }}!
            <a href ="{% url 'user-profile' user.pk %}">Профиль</a>
        {% endif %}

        <a href ="{% url 'all-products' %}">Товары</a>
        {% if request.user.is_authenticated %}
        <a href="{% url 'orders:list' %}">Мои заказы</a>
        <a href="{% url 'cart' %}">Корзина</a>
        <a href="{% url 'logout' %}">Выход</a>
        {% else %}
        <a href="{% url 'login' %}">Вход</a> | <a href="{% url 'register' %}">Регистрация</a>
        {% endif %}
    </li>
</ul>

{% block content %}

{% endblock  %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <p>Добро пожаловать на сайт Aesthetic - компании, специализирующейся на производстве высококачественных изделий из гипса.
        Наша компания уже много лет занимается производством уникальных декоративных изделий, которые способны преобразить любое помещение.
        Мы гордимся тем, что наши изделия отличаются высоким качеством, прекрасным дизайном и неповторимым стилем.
        Мы используем только лучшие материалы и тщательно следим за каждым этапом производства, чтобы обеспечить нашим клиентам продукцию высочайшего качества.</p>
{% endblock %}